### PR TITLE
New layout simplified [WIP]

### PR DESCRIPTION
**Pull request by alexhking**

### CODE REVIEW

**Comment by karaokewtf** [comment]
📦 archival: Deployed to [preview.archival.dev/pr/4](https://preview.archival.dev/pr/4)

**Comment by karaokewtf** [comment]
📦 archival: Deployed to [preview.archival.dev/pr/4](https://preview.archival.dev/pr/4)

**Comment by karaokewtf** [comment]
📦 archival: Deployed to [preview.archival.dev/pr/4](https://preview.archival.dev/pr/4)

**Review by jesseditson — APPROVED** [review]
Hooray!

**Pull request merged**
